<?php
require_once __DIR__ . '/../core/Controller.php';
require_once __DIR__ . '/../models/ReferenceModel.php';
class ReferenceController extends Controller {
    public function kategoriProduk(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); $this->view('referensi/kategori_produk/index',['title'=>'Referensi Kategori Produk','rows'=>$m->kategoriProdukAll(current_umkm_id())]); }
    public function kategoriProdukCreate(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); if(is_post()){ csrf_check(); $m->kategoriProdukCreate($_POST,current_umkm_id()); flash('success','Kategori produk berhasil ditambahkan.'); $this->redirect('index.php?page=referensi-kategori-produk'); } $this->view('referensi/kategori_produk/form',['title'=>'Tambah Kategori Produk','row'=>null]); }
    public function kategoriProdukEdit(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); $id=(int)($_GET['id']??0); $row=$m->kategoriProdukFind($id,current_umkm_id()); if(!$row){ flash('error','Data tidak ditemukan.'); $this->redirect('index.php?page=referensi-kategori-produk'); } if(is_post()){ csrf_check(); $m->kategoriProdukUpdate($id,$_POST,current_umkm_id()); flash('success','Kategori produk berhasil diubah.'); $this->redirect('index.php?page=referensi-kategori-produk'); } $this->view('referensi/kategori_produk/form',['title'=>'Edit Kategori Produk','row'=>$row]); }
    public function kategoriProdukDelete(): void { require_roles('super_admin','admin_umkm'); csrf_check(); (new ReferenceModel())->kategoriProdukDelete((int)($_POST['id']??0), current_umkm_id()); flash('success','Kategori produk berhasil dihapus.'); $this->redirect('index.php?page=referensi-kategori-produk'); }

    public function satuan(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); $this->view('referensi/satuan/index',['title'=>'Referensi Satuan','rows'=>$m->satuanAll()]); }
    public function satuanCreate(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); if(is_post()){ csrf_check(); $m->satuanCreate($_POST); flash('success','Satuan berhasil ditambahkan.'); $this->redirect('index.php?page=referensi-satuan'); } $this->view('referensi/satuan/form',['title'=>'Tambah Satuan','row'=>null]); }
    public function satuanEdit(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); $id=(int)($_GET['id']??0); $row=$m->satuanFind($id); if(!$row){ flash('error','Data tidak ditemukan.'); $this->redirect('index.php?page=referensi-satuan'); } if(is_post()){ csrf_check(); $m->satuanUpdate($id,$_POST); flash('success','Satuan berhasil diubah.'); $this->redirect('index.php?page=referensi-satuan'); } $this->view('referensi/satuan/form',['title'=>'Edit Satuan','row'=>$row]); }
    public function satuanDelete(): void { require_roles('super_admin','admin_umkm'); csrf_check(); (new ReferenceModel())->satuanDelete((int)($_POST['id']??0)); flash('success','Satuan berhasil dihapus.'); $this->redirect('index.php?page=referensi-satuan'); }

    public function kategoriKas(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); $this->view('referensi/kategori_kas/index',['title'=>'Referensi Kategori Kas','rows'=>$m->kategoriKasAll(current_umkm_id())]); }
    public function kategoriKasCreate(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); if(is_post()){ csrf_check(); $m->kategoriKasCreate($_POST,current_umkm_id()); flash('success','Kategori kas berhasil ditambahkan.'); $this->redirect('index.php?page=referensi-kategori-kas'); } $this->view('referensi/kategori_kas/form',['title'=>'Tambah Kategori Kas','row'=>null]); }
    public function kategoriKasEdit(): void { require_roles('super_admin','admin_umkm'); $m=new ReferenceModel(); $id=(int)($_GET['id']??0); $row=$m->kategoriKasFind($id,current_umkm_id()); if(!$row){ flash('error','Data tidak ditemukan.'); $this->redirect('index.php?page=referensi-kategori-kas'); } if(is_post()){ csrf_check(); $m->kategoriKasUpdate($id,$_POST,current_umkm_id()); flash('success','Kategori kas berhasil diubah.'); $this->redirect('index.php?page=referensi-kategori-kas'); } $this->view('referensi/kategori_kas/form',['title'=>'Edit Kategori Kas','row'=>$row]); }
    public function kategoriKasDelete(): void { require_roles('super_admin','admin_umkm'); csrf_check(); (new ReferenceModel())->kategoriKasDelete((int)($_POST['id']??0), current_umkm_id()); flash('success','Kategori kas berhasil dihapus.'); $this->redirect('index.php?page=referensi-kategori-kas'); }
}
